name: Backend Tests

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.TEST_MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.TEST_MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          install: true

      - name: Build and test
        env:
          MYSQL_HOST: ${{ secrets.TEST_MYSQL_HOST }}
          MYSQL_PORT: ${{ secrets.TEST_MYSQL_PORT }}
          MYSQL_USER: ${{ secrets.TEST_MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.TEST_MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.TEST_MYSQL_DATABASE }}
        run: |
          docker compose build api
          docker compose run --rm api go test ./... -v

      - name: Run lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: backend 