name: EC2 Backend Deploy

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'backend/**'
      - 'infra/v2/**'
    # branches:
    #   - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-northeast-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Verify EC2 connection
        run: |
          echo "Verifying connection to EC2 instance..."
          echo "EC2 Instance IP: ${{ secrets.EC2_INSTANCE_IP }}"

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          # 秘密鍵をGitHub Secretsから取得してファイルに保存
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/ai-sales-copy-api-key.pem
          chmod 400 ~/.ssh/ai-sales-copy-api-key.pem
          
          # SSH Host Key の検証をスキップ（初回接続用）
          echo "Host *" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deploy application to EC2
        run: |
          PUBLIC_IP="${{ secrets.EC2_INSTANCE_IP }}"
          
          # EC2インスタンスに接続してアプリケーションを更新
          ssh -i ~/.ssh/ai-sales-copy-api-key.pem ec2-user@$PUBLIC_IP << 'EOF'
            set -e
            
            echo "=== Updating application ==="
            cd /opt/api
            
            # 最新のコードを取得（現在のブランチ）
            sudo git fetch origin ${{ github.ref_name }}
            sudo git reset --hard origin/${{ github.ref_name }}
            
            # backendディレクトリに移動してビルド
            cd backend
            
            # Goアプリケーションのビルド
            /usr/local/go/bin/go mod download
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 /usr/local/go/bin/go build -o main ./cmd/api
            
            # 所有者を正しく設定
            sudo chown -R ec2-user:ec2-user /opt/api
            
            # APIサービスの再起動
            sudo systemctl restart api
            
            # ステータス確認
            sudo systemctl status api --no-pager -l
            
            echo "=== Deployment completed ==="
          EOF

      - name: Verify deployment
        run: |
          PUBLIC_IP="${{ secrets.EC2_INSTANCE_IP }}"
          
          # アプリケーションの起動を少し待つ
          sleep 30
          
          # ヘルスチェック（ポート8080での確認）
          ssh -i ~/.ssh/ai-sales-copy-api-key.pem ec2-user@$PUBLIC_IP << 'EOF'
            echo "=== Checking application health ==="
            
            # APIサービスの状態確認
            sudo systemctl is-active api
            
            # ポートリスニング確認
            sudo netstat -tlnp | grep :8080 || echo "Port 8080 not found"
            
            # アプリケーションログの最後の数行を表示
            echo "=== Recent application logs ==="
            sudo journalctl -u api --no-pager -n 10
          EOF

      - name: Configure SSL certificate
        run: |
          PUBLIC_IP="${{ secrets.EC2_INSTANCE_IP }}"
          
          # SSL証明書の設定（Let's Encrypt）
          ssh -i ~/.ssh/ai-sales-copy-api-key.pem ec2-user@$PUBLIC_IP << 'EOF'
            echo "=== Configuring SSL certificate ==="
            
            # certbotでSSL証明書を取得（非対話モード）
            sudo certbot --nginx -d api.ai-sales-copy-generator.click --non-interactive --agree-tos --email admin@ai-sales-copy-generator.click --redirect || true
            
            # nginx設定の再読み込み
            sudo systemctl reload nginx
            
            # nginx状態確認
            sudo systemctl status nginx --no-pager -l
          EOF

      - name: Display deployment info
        run: |
          echo "=== Deployment Summary ==="
          echo "Public IP: ${{ secrets.EC2_INSTANCE_IP }}"
          echo "API Endpoint: https://api.ai-sales-copy-generator.click"
          echo "SSH Command: ssh -i ~/.ssh/ai-sales-copy-api-key.pem ec2-user@${{ secrets.EC2_INSTANCE_IP }}"
          echo "Deployment completed successfully!" 