name: Frontend Tests

on:
  push:
    # 元の条件（必要になったらコメントを外す）
    # paths:
    #   - 'frontend/**'
    #   - '.github/workflows/frontend-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Docker Buildxのセットアップとキャッシュの設定
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          install: true

      # Dockerイメージのキャッシュを復元
      - name: Cache Docker images
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # フロントエンドとAPIのコンテナを並列でビルド
      - name: Build containers
        uses: docker/bake-action@v4
        with:
          push: false
          set: |
            *.cache-from=type=local,src=/tmp/.buildx-cache
            *.cache-to=type=local,dest=/tmp/.buildx-cache-new
          files: |
            docker-compose.yml
          load: true

      # キャッシュの更新
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # Playwrightのブラウザをキャッシュ
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: frontend/pw-browsers
          key: ${{ runner.os }}-pw-browsers-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-pw-browsers-

      # コンテナを起動してテストを実行
      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ENV_FILE: ""
          DEBUG: 'true'
        run: |
          docker compose --profile frontend-test up -d
          docker compose --profile frontend-test exec -T frontend-test npx playwright install --with-deps
          docker compose --profile frontend-test exec -T frontend-test npm run test:unit
          docker compose --profile frontend-test exec -T frontend-test npm run test:e2e

      # エラー時のログ出力
      - name: Show logs (on failure)
        if: failure()
        run: |
          docker compose logs frontend-test
          docker compose logs api-test 