name: Frontend Tests

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          install: true

      - name: Run frontend tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # テスト環境の構築
          docker compose --profile frontend-test up -d
          
          # APIサーバーのログを表示
          docker compose --profile frontend-test logs api-test
          
          # ユニットテストの実行
          docker compose --profile frontend-test run --rm -e OPENAI_API_KEY=$OPENAI_API_KEY frontend-test npm run test:unit
          
          # E2Eテストの実行
          docker compose --profile frontend-test run --rm -e OPENAI_API_KEY=$OPENAI_API_KEY frontend-test npm run test:e2e 