name: Frontend Tests

on:
  push:
    # 元の条件（必要になったらコメントを外す）
    # paths:
    #   - 'frontend/**'
    #   - '.github/workflows/frontend-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Docker Buildxのセットアップとキャッシュの設定
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          install: true

      # フロントエンドとAPIのコンテナを並列でビルド
      - name: Build containers
        run: |
          docker compose --profile frontend-test build

      # Playwrightのブラウザをキャッシュ
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: frontend/pw-browsers
          key: ${{ runner.os }}-pw-browsers-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-pw-browsers-

      # コンテナを起動してテストを実行
      - name: Start containers
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Checking for OPENAI_API_KEY..."
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "::error::Repository secret OPENAI_API_KEY is not set or empty. Please configure it in Settings > Secrets and variables > Actions."
            exit 1
          fi
          echo "OPENAI_API_KEY is set."
          
          export OPENAI_API_KEY=$OPENAI_API_KEY
          docker compose --profile frontend-test up --build -d --wait

      - name: Run tests
        run: |
          docker compose --profile frontend-test exec -T frontend-test sh -c "npx playwright install --with-deps && npm run test:unit && npm run test:e2e"

      # エラー時のログ出力
      - name: Show logs (on failure)
        if: failure()
        run: |
          docker compose logs frontend-test
          docker compose logs api-test 