name: Build and Push Lambda Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'
      - 'backend/Dockerfile.lambda'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Production
    env:
      AWS_REGION: ap-northeast-1
      ECR_REPOSITORY: ai-sales-copy-generator-lambda
      ECR_URI: 148493853021.dkr.ecr.ap-northeast-1.amazonaws.com/ai-sales-copy-generator-lambda
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Lambda image (linux/amd64)
        run: |
          docker buildx build --platform linux/amd64 -f backend/Dockerfile.lambda -t $ECR_URI:latest --push backend 